# Generated by Django 5.1.2 on 2024-10-17 16:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'providers',
                'indexes': [models.Index(fields=['name'], name='providers_name_7e730c_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_provider_name')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='coreapp.provider')),
            ],
            options={
                'db_table': 'service_areas',
                'indexes': [models.Index(fields=['name'], name='service_are_name_43b448_idx'), django.contrib.postgres.indexes.GistIndex(fields=['area'], name='service_are_area_cf04c0_gist')],
            },
        ),
    ]
