# Generated by Django 5.1.2 on 2024-10-16 18:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'providers',
                'indexes': [models.Index(fields=['name'], name='providers_name_7e730c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('localtion', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.provider')),
            ],
            options={
                'db_table': 'service_areas',
                'indexes': [models.Index(fields=['name'], name='service_are_name_43b448_idx'), models.Index(fields=['localtion'], name='service_are_localti_57b138_idx')],
            },
        ),
    ]
